-- 1. Create a public users table that maps to auth.users
CREATE TABLE public.users (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  role TEXT DEFAULT 'employee' CHECK (role IN ('employee', 'admin')),
  device_info TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure the public users table can be read by anonymous/authenticated users if needed 
-- (Assuming Server-Side mostly, but good practice to enable RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.users FOR SELECT USING (true);
CREATE POLICY "Allow service role full access" ON public.users USING (true);

-- 2. Create the attendance table
CREATE TABLE public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) NOT NULL,
  date DATE NOT NULL,
  tap_in TIMESTAMP WITH TIME ZONE,
  break_start TIMESTAMP WITH TIME ZONE,
  break_end TIMESTAMP WITH TIME ZONE,
  tap_out TIMESTAMP WITH TIME ZONE,
  status TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.attendance FOR SELECT USING (true);
CREATE POLICY "Allow service role full access" ON public.attendance USING (true);

-- 3. Create your first admin user here if you need to bypass python logic 
-- (Or just use your frontend with the API key after running python backend).
